version: '3.7'

services:
  db:
    image: mysql:5.7
    container_name: mysql1
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=hr_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    volumes:
      - ./volumes/mysql_data:/var/lib/mysql
    networks:
      - db_network

  # Redis
  cache:
    image: redis:6.2-alpine
    container_name: redis1
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - ./volumes/cache:/data

volumes:
  mysql_data:
  cache:
networks:
  db_network:
